name: ESLint - Testing
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches:
      - 'master'
    paths-ignore:
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs all global dependencies
        run: npm i -g eslint
      - name: Installs all local dependencies
        run: npm i
      - name: Checks for any errors in JavaScript ESLint
        run: |
          chmod +x ./tests/js/lint.sh
          ./tests/js/lint.sh
      - name: Checks for any errors in TypeScript ESLint
        run: |
          chmod +x ./tests/ts/lint.sh
          ./tests/ts/lint.sh